-- AlterTable
ALTER TABLE "Vehicle" ADD COLUMN     "carteGrise" TEXT,
ADD COLUMN     "centreCout" TEXT,
ADD COLUMN     "code" TEXT,
ADD COLUMN     "codeCle" TEXT,
ADD COLUMN     "commentaire" TEXT,
ADD COLUMN     "concessionnaire" TEXT,
ADD COLUMN     "couleur" TEXT,
ADD COLUMN     "dateAchat" TIMESTAMP(3),
ADD COLUMN     "dateMiseEnCirculation" TIMESTAMP(3),
ADD COLUMN     "datePrevueRestitution" TIMESTAMP(3),
ADD COLUMN     "garantie" TEXT,
ADD COLUMN     "immatricule" TEXT,
ADD COLUMN     "indiceHoraireInitial" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "kilometrageInitial" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "modele" TEXT,
ADD COLUMN     "montantHT" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "nom" TEXT,
ADD COLUMN     "numeroChassis" TEXT,
ADD COLUMN     "numeroContrat" TEXT,
ADD COLUMN     "numeroOrdre" TEXT,
ADD COLUMN     "numeroW" TEXT,
ADD COLUMN     "photoPrincipale" TEXT,
ADD COLUMN     "tva" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "typeAcquisition" TEXT DEFAULT 'ACHAT',
ALTER COLUMN "type" DROP NOT NULL,
ALTER COLUMN "type" SET DEFAULT 'VAN',
ALTER COLUMN "seats" DROP NOT NULL,
ALTER COLUMN "seats" SET DEFAULT 1;
